 
   - name: Add a new user named devops
     user:
          name=devops
          password={{ devops_password }}
 
   - name: Add devops user to the sudoers
     copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops  ALL=(ALL)  NOPASSWD: ALL"
 
   - name: Deploy SSH Key
     authorized_key: user=devops
                     key="{{ lookup('file', 'devops_id_rsa.pub') }}"
                     state=present
