 
   - name: Add a new user named devops
     user:
          name={{username}}
          password={{ devops_password }}
 
   - name: Add devops user to the sudoers
     copy:
          dest: "/etc/sudoers.d/{{username}}"
          content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"
 
   - name: Deploy SSH Key
     authorized_key: user={{username}}
                     key="{{ lookup('file', 'id_rsa.pub') }}"
                     state=present
                     
   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
           
     notify:
        - restart ssh
